### ISSUE TITLE
Add full example in Readme

### ISSUE THREAD

**Issue by patrickfav** [timfreiheit/ResourcePlaceholdersPlugin#1]
Right now the user has to guess how it works in details. Provide a full minimal example on how to use it (like in your SO answer) e.g.

```
<shortcuts xmlns:android="http://schemas.android.com/apk/res/android">
<shortcut
    ...>

    <intent
        android:action="android.intent.action.VIEW"
        android:targetClass="com.test.MainActivity"
        android:targetPackage="${applicationId}"/>
</shortcut>
```

**Comment by timfreiheit** [comment]
you are right.
i updated the readme and hope it is now easier to understand without looking into the sample project
