### ISSUE TITLE
Add plugin to jcenter

### ISSUE THREAD

**Issue by patrickfav** [timfreiheit/ResourcePlaceholdersPlugin#2]
Please :)

**Comment by ldrrp** [comment]
I would say just leave it, why make him double publish, jitpack works fine.

**Comment by drakeet** [comment]
Using too many repositories can cause **sync** to be very slow, so I also want to be able to publish to jcenter so that we can import it more easily and avoid the need to synchronize multiple repositories and cause a lot of time.

**Comment by timfreiheit** [comment]
this can be closed until https://github.com/timfreiheit/ResourcePlaceholdersPlugin/issues/4 is resolved right?
