### ISSUE TITLE
Add plugin to Gradle plugin portal

### ISSUE THREAD

**Issue by davidmigloz** [timfreiheit/ResourcePlaceholdersPlugin#4]
It'd nice if the plugin is available in the [Gradle plugin portal](https://plugins.gradle.org/), so we can [apply the plugin with the plugins DSL](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block). Thanks 😄

**Comment by timfreiheit** [comment]
Thank you for the helpful link. The plugin approval is now pending on the gradle plugin portal.
Let's see how this works out.

**Comment by timfreiheit** [comment]
the plugin is now available. https://plugins.gradle.org/plugin/de.timfreiheit.resourceplaceholders
unfortunately the plugins dsl can not be used at the moment. The plugin must be applied after the android plugin which seems not to be possible using the dsl.
I need to invest further if this can be solved.

**Comment by timfreiheit** [comment]
Version 0.3 of the plugin now supports the plugins DSL 🎉
